//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Aranda.WEB.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FT_Aranda.WEB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/login/Authenticate.
        /// </summary>
        internal static string API_LOGIN_AUTHENTICATE {
            get {
                return ResourceManager.GetString("API_LOGIN_AUTHENTICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/CreateUser.
        /// </summary>
        internal static string API_USER_CREATE {
            get {
                return ResourceManager.GetString("API_USER_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/DeletUser.
        /// </summary>
        internal static string API_USER_DELETE {
            get {
                return ResourceManager.GetString("API_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/GetUserById.
        /// </summary>
        internal static string API_USER_GETBYID {
            get {
                return ResourceManager.GetString("API_USER_GETBYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/GetUserLikeFirtsName.
        /// </summary>
        internal static string API_USER_GETFIRTSNAME {
            get {
                return ResourceManager.GetString("API_USER_GETFIRTSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/GetUserLikeLastName.
        /// </summary>
        internal static string API_USER_GETLASTNAME {
            get {
                return ResourceManager.GetString("API_USER_GETLASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/GetUsers.
        /// </summary>
        internal static string API_USER_GETUSERS {
            get {
                return ResourceManager.GetString("API_USER_GETUSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/user/UpdateUser.
        /// </summary>
        internal static string API_USER_UPDATE {
            get {
                return ResourceManager.GetString("API_USER_UPDATE", resourceCulture);
            }
        }
    }
}
